# Retos {.unnumbered}

## Reto #1: Conversi贸n r谩pida a number {#sec-array-1}

::: {.callout-caution title="Dificultad" collapse="true"}
**Intermedio**
:::

**驴Qu茅 crees que imprime el siguiente c贸digo?**

```js
const array = [true, 33, 9, "-2"];

const f = (arr) => {
  return arr.map(Number)
}
const result = f(array)
console.log(result)
```

**Pista:** Piensa en c贸mo `Number()` convierte diferentes tipos.

* A. `[1, 33, 9, -2]`
* B. `[boolean, 33, 9, string]`
* C. `[null, 33, 9, null]`
* D. `[undefined, 33, 9, undefined]`

**[Ver soluci贸n](#sec-sol-array-1)**

---

## Reto #2: Desestructuraci贸n de arreglos {#sec-array-2}

::: {.callout-caution title="Dificultad" collapse="true"}
**Intermedio**
:::

**驴Qu茅 crees que imprime el siguiente c贸digo?**

```js
const fruits = ["Mango", "Manzana", "Naranja", "Pera"];
const { 3:pear } = fruits;
console.log(pear);
```

**Pista:** Es simplemente una desestructuraci贸n de arreglos.

* A. `Uncaught TypeError : cannot read property`
* B. `TypeError: null is not an object (evaluating)`
* C. `Naranja`
* D. `Pera`

**[Ver soluci贸n](#sec-sol-array-2)**

---

## Reto #3: Igualdad d茅bil vs Igualdad estricta {#sec-array-3}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Puedes explicar el siguiente c贸digo?**

```js
console.log(false == 0) // true
console.log(false === 0) // false
```

**Pista:** Notar la comparaci贸n de variables con igualdad d茅bil e igualdad estricta.

**[Ver soluci贸n](#sec-sol-array-3)**

---

## Reto #4: Comparaci贸n de valores falsy {#sec-array-4}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Puedes explicar el siguiente c贸digo?**

```js
console.log(false == null); // false
console.log(false == undefined); // false
```

Siendo `null` y `undefined` valores falsy, 驴por qu茅 pasa esto?

**Pista:** Notar que todos los valores de la comparaci贸n son considerados valores falsy para el interprete de JavaScript 

**[Ver soluci贸n](#sec-sol-array-4)**

---

## Reto #5: Igualdad estricta con `NaN` {#sec-array-5}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Puedes explicar el siguiente c贸digo?**

```js
console.log(NaN === NaN) // false
```

驴Por qu茅 pasa esto?

**Pista:** Piensa en la naturaleza de `NaN`. 

**[Ver soluci贸n](#sec-sol-array-5)**

---

## Reto #6: Copia de objetos por referencia  {#sec-array-6}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Puedes explicar el siguiente c贸digo?**

```js
let c = { greeting: "Hey!" };
let d;

d = c;
c.greeting = "Hello";
console.log(d.greeting);
```

**Pista:** Recordar las diferencias de las copias por valor y copias por referencia.

* A. `Hello`
* B. `undefined`
* C. `ReferenceError`
* D. `TypeError`

**[Ver soluci贸n](#sec-sol-array-6)**

---

## Reto #7: El operador `+` y `!`  {#sec-array-7}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
console.log(+true);
console.log(!"Messi")
```

**Pista:** Recuerda los conceptos de valores falsy y truthy.

* A. `1`, `false`
* B. `false`, `NaN`
* C. `false`, `false`
* D. `Ninguno de los anteriores`

**[Ver soluci贸n](#sec-sol-array-7)**

---

## Reto #8: Comparaciones entre primitivos y objetos {#sec-array-8}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
let a = 3;
let b = new Number(3);
let c = 3;

console.log(a == b);
console.log(a === b);
console.log(b === c);
```

**Pista:** Notar la diferencia entre `==` y `===`. Notar que `b` es un objeto y no primitivo.

* A. `true`, `false`, `true`
* B. `false`, `false`, `true`
* C. `true`, `false`, `false`
* D. `false`, `true`, `true`

**[Ver soluci贸n](#sec-sol-array-8)**

---

## Reto #9: Una curiosidad sobre funciones  {#sec-array-9}

::: {.callout-caution title="Dificultad" collapse="true"}
**Intermedio**
:::

**驴Qu茅 imprime este c贸digo?**

```js
function bark() {
  console.log("Woof!");
}

bark.animal = "dog";
```

**Pista:** Todo en JavaScript es una funci贸n.

* A. `No pasa nada, es totalmente correcto.`
* B. `SyntaxError. No es posible agregar propiedades a una funci贸n de esta manera.`
* C. `undefined`
* D. `ReferenceError`

**[Ver soluci贸n](#sec-sol-array-9)**

---

## Reto #10: Variables sin `var`, `let` o `const` {#sec-array-10}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
let greeting;
greetign = {}; // Typo!
console.log(greetign);
```

**Pista:** 驴Qu茅 pasa cuando declaramos una variable sin `var`, `let` o `const`? 驴Piensas que es posible hacer algo as铆 o tendremos alg煤n tipo de error por parte de JavaScript?

* A. `{}`
* B. `ReferenceError: greetign is not defined`
* C. `undefined`
* D. `Ninguna de las anteriores`

**[Ver soluci贸n](#sec-sol-array-10)**

---


## Reto #11: Operadores `+` y `-` con cadenas y n煤meros {#sec-array-11}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
const x = "111"
const y = 11
let z = "1"

console.log(x + y)
console.log(y - z)
```

**Pista:** Diferenciar una suma artim茅tica de una concatenaci贸n de cadenas.

* A. `122`, `10`
* B. `"11111"`, `1`
* C. `"11111"`, `10`
* D. `122`, `"111"`

**[Ver soluci贸n](#sec-sol-array-11)**

---

## Reto #12: Comparaci贸n de objetos {#sec-array-12}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
function checkAge(data) {
  if (data === { age: 18 }) {
    console.log("You are an adult!");
  } else if (data == { age: 18 }) {
    console.log("You are still an adult.");
  } else {
    console.log(`Hmm... You don't have an age I guess`);
  }
}

const result = checkAge({ age: 18 });
console.log(result);
```

**Pista:** Recordar que los objetos se almacenan en memoria teniendo en cuenta su **referencia** y no su **valor**.

* A. `You are an adult!`
* B. `You are still an adult.`
* C. `Hmm... You don't have an age I guess`
* D. `Ninguna de las anteriores`

**[Ver soluci贸n](#sec-sol-array-12)**

---

## Reto #13: Par谩metros REST {#sec-array-13}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
function getAge(...args) {
  console.log(typeof args);
}

getAge(21);
```

**Pista:** Los par谩metros REST permiten pasar un n煤mero variable de argumentos a una funci贸n.

* A. `number`
* B. `array`
* C. `objet`
* D. `NaN`

**[Ver soluci贸n](#sec-sol-array-13)**

---

## Reto #14: `typeof` de expresiones extra帽as {#sec-array-14}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
console.log(typeof([] + []));
```

**Pista:** Recuerda el el operador `+` sirve para hacer concatenaciones de cadenas.

* A. `undefined`
* B. `number`
* C. `object`
* D. `string`

**[Ver soluci贸n](#sec-sol-array-14)**

---

## Reto #15: Objetos y conjuntos {#sec-array-15}

::: {.callout-caution title="Dificultad" collapse="true"}
**Avanzado**
:::

**驴Qu茅 imprime este c贸digo?**

```js
const obj = { 1: "a", 2: "b", 3: "c" };
const set = new Set([1, 2, 3, 4, 5]);

obj.hasOwnProperty("1");
obj.hasOwnProperty(1);
set.has("1");
set.has(1);
```

**Pista:** Recuerda que un `set` no es lo mismo que un objeto.

* A. `false`, `true`, `false`, `true`
* B. `false`, `true`, `true`, `true`
* C. `true`, `true`, `false`, `true`
* D. `true`, `true`, `true`, `true`

**[Ver soluci贸n](#sec-sol-array-15)**

---

## Reto #16: Una curiosidad sobre los objetos {#sec-array-16}

::: {.callout-caution title="Dificultad" collapse="true"}
**Intermedio**
:::

**驴Qu茅 imprime este c贸digo?**

```js
const obj = { a: "one", b: "two", a: "three" };
console.log(obj);
```

**Pista:** Los objetos son estructuras de datos no indexadas.

* A. `{ a: "one", b: "two" }`
* B. `{ b: "two", a: "three" }`
* C. `{ a: "three", b: "two" }`
* D. `SyntaxError`

**[Ver soluci贸n](#sec-sol-array-16)**

---

## Reto #17: Hablemos sobre prototipos  {#sec-array-17}

::: {.callout-caution title="Dificultad" collapse="true"}
**Intermedio**
:::

**驴Qu茅 imprime este c贸digo?**

```js
String.prototype.giveLydiaPizza = () => {
  return "Just give Lydia pizza already!";
};

const name = "Lydia";

name.giveLydiaPizza();
```

**Pista:** Los objetos son estructuras de datos no indexadas.

* A. `"Just give Lydia pizza already!"`
* B. `TypeError: not a function`
* C. `SyntaxError`
* D. `undefined`

**[Ver soluci贸n](#sec-sol-array-17)**

---

## Reto #18: Simulando asincron铆a con `setTimeOut()` {#sec-array-18}

::: {.callout-caution title="Dificultad" collapse="true"}
**Intermedio**
:::

**驴Qu茅 imprime este c贸digo?**

```js
const foo = () => console.log("First");
const bar = () => setTimeout(() => console.log("Second"));
const baz = () => console.log("Third");

bar();
foo();
baz();
```

**Pista:** `setTimeout` es una Web API.

* A. `First`, `Second`, `Third`
* B. `First`, `Third`, `Second`
* C. `Second`, `First`, `Third`
* D. `Second`, `Third`, `First`

**[Ver soluci贸n](#sec-sol-array-18)**

---

## Reto #19: `typeof` de `typeof` {#sec-array-19}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
console.log(typeof typeof 1);
```

**Pista:** `typeof` retorna un primitivo. 驴Pero cu谩l?

* A. `number`
* B. `string`
* C. `object`
* D. `undefined`

**[Ver soluci贸n](#sec-sol-array-19)**

---

## Reto #20: Posiciones indexadas de un arreglo {#sec-array-20}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
const numbers = [1, 2, 3];
numbers[10] = 11;
console.log(numbers);
```

**Pista:** Los arreglos en JavaScript son muy permisivos.

* A. `[1, 2, 3, 7 x null, 11]`
* B. `[1, 2, 3, 11]`
* C. `[1, 2, 3, 7 x empty, 11]`
* D. `SyntaxError`

**[Ver soluci贸n](#sec-sol-array-20)**

---

## Reto #21: Entendiendo `reduce` con matrices  {#sec-array-21}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
[[0, 1], [2, 3]].reduce(
  (acc, cur) => {
    return acc.concat(cur);
  },
  [1, 2]
);
```

**Pista:** El segundo par谩metro de `reduce` es el valor inicial de `acc`.

* A. `[0, 1, 2, 3, 1, 2]`
* B. `[6, 1, 2]`
* C. `[1, 2, 0, 1, 2, 3]`
* D. `[1, 2, 6]`

**[Ver soluci贸n](#sec-sol-array-21)**

---

## Reto #22: El operador de doble negaci贸n  {#sec-array-22}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
console.log(!!null);
console.log(!!"");
console.log(!!1);
```

**Pista:** El operador `!!` convierte un valor en su equivalente booleano.

* A. `false`, `true`, `false`
* B. `false`, `false`, `true`
* C. `false`, `true`, `true`
* D. `true`, `true`, `false`

**[Ver soluci贸n](#sec-sol-array-22)**

---

## Reto #23: Uso de `setInterval` {#sec-array-23}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
setInterval(() => console.log("Hi"), 1000);
```

**Pista:** `setInterval` es una Web API que se ejecuta cada x milisegundos.

* A. `1000`
* B. `Hi 1000 veces`
* C. `Hi cada segundo`
* D. `undefined`

**[Ver soluci贸n](#sec-sol-array-23)**

---

## Reto #24: Spread operator con cadenas {#sec-array-24}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
console.log([..."Oscar"])
```

**Pista:** El **spread operator** permite expandir un iterable en sus elementos.

* A. `["O", "s", "c", "a", "r"]`
* B. `["Oscar"]`
* C. `[[], "Oscar"]`
* D. `[["O", "s", "c", "a", "r"]]`

**[Ver soluci贸n](#sec-sol-array-24)**

---

## Reto #25: Objeto por referencia {#sec-array-25}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
let person = { name: "Carmen" };
const members = [person];
person = null;

console.log(members);
```

**Pista:** Los objetos pasan sus valores por referencia.

* A. `null`
* B. `[null]`
* C. `[{}]`
* D. `[{ name: "Carmen" }]`

**[Ver soluci贸n](#sec-sol-array-25)**

---

## Reto #26: El bucle `for...in` con objetos {#sec-array-26}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
const person = {
  name: "Carla",
  age: 26
};

for (const item in person) {
  console.log(item);
}
```

**Pista:** El bucle `for...in` no itera sobre los valores de un objeto.

* A. `{ name: "Carla" }`, `{ age: 26 }`
* B. `"name"`, `"age"`
* C. `"Carla"`, `26`
* D. `["name", "Carla"]`, `["age", 26]`

**[Ver soluci贸n](#sec-sol-array-26)**

---

## Reto #27: 驴Concatenaciones o sumas aritm茅ticas? {#sec-array-27}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
console.log(3 + 4 + "5");
```

**Pista:** Los n煤meros se suman, las cadenas se concatenan.

* A. `"345"`
* B. `"75"`
* C. `12`
* D. `75`

**[Ver soluci贸n](#sec-sol-array-27)**

---

## Reto #28: Conversiones con `parseInt()` {#sec-array-28}

::: {.callout-caution title="Dificultad" collapse="true"}
**Intermedio**
:::

**驴Qu茅 imprime este c贸digo?**

```js
const num = parseInt("7*6", 10);
console.log(num); 
```

**Pista:** `parseInt()` convierte un n煤mero a una base n煤merica dada.

* A. `42`
* B. `"42"`
* C. `7`
* D. `NaN`

**[Ver soluci贸n](#sec-sol-array-28)**

---

## Reto #29: Transformaciones de arreglos con `map()` {#sec-array-29}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
[1, 2, 3].map(num => {
  if (typeof num === "number") return;
  return num * 2;
});
```

**Pista:** Ojo con la sentencia `return`

* A. `[]`
* B. `[null, null, null]`
* C. `[undefined, undefined, undefined]`
* D. `[ 3 huecos vac铆os ]`

**[Ver soluci贸n](#sec-sol-array-29)**

---

## Reto #30: Alcance de variables {#sec-array-30}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
let x = 10;
if (true) {
  let y = 20;
  var z = 30;
  console.log(x + y + z);
}
console.log(x + z);
```

**Pista:** Diferenciar los diferentes alcances de las variables con `let` y `var`.

* A. `60`, `40`
* B. `undefined`, `10`
* C. `50`, `10`
* D. `null`, `40`

**[Ver soluci贸n](#sec-sol-array-30)**

---

## Reto #31: Otra desestructuraci贸n de arreglos {#sec-array-31}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
const fn = () => {
  return [1000, 9000+1]
}

const [, second] = fn()
console.log(second.toString())
```

**Pista:** Es posible omitir posiciones no deseadas del arreglo usando `,` en la desestructuraci贸n.

* A. `1000`
* B. `9001`
* C. `"9001"`
* D. `SyntaxError`

**[Ver soluci贸n](#sec-sol-array-31)**

---

## Reto #32: Funciones Tradicionales vs Funciones Flecha {#sec-array-32}

::: {.callout-caution title="Dificultad" collapse="true"}
**Intermedio**
:::

**Explica este c贸digo JavaScript**

驴Cu谩l es la diferencia entre las siguientes funciones?

```js
function addTraditional(a, b){
  return a + b;
}

const addArrow = (a, b) => {
  return a + b;
}
```

**Pista:** No tiene nada que ver con la sintaxis.

* A. `No hay diferencia, son exactamente iguales.`
* B. `La primera funci贸n es m谩s r谩pida que la segunda.`
* C. `La primera funci贸n tiene hoisting, la segunda no.`
* D. `Solo cambia la sintaxis, luego son iguales.`

**[Ver soluci贸n](#sec-sol-array-32)**

---

## Reto #33: Excepciones con `try...catch` {#sec-array-33}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
function greeting() {
  throw "Hello world!";
}

function sayHi() {
  try {
    const data = greeting();
    console.log("It worked!", data);
  } catch (e) {
    console.log("Oh no an error!", e);
  }
}

sayHi();
```

**Pista:** La sentencia `catch` siempre atrapa los errores.

* A. `"It worked! Hello world!"`
* B. `"Oh no an error!" undefined`
* C. `SyntaxError: can only throw Error objects`
* D. `"Oh no an error! Hello world!"`

**[Ver soluci贸n](#sec-sol-array-33)**

---

## Reto #34: Spread operator con objetos {#sec-array-34}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
const user = { name: "Hernan", age: 21 };
const admin = { admin: true, ...user };

console.log(admin);
```

**Pista:** El **spread operator** expande las propiedades del objeto. 

* A. `{ admin: true, user: { name: "Hernan", age: 21 } }`
* B. `{ admin: true, name: "Hernan", age: 21 }`
* C. `{ admin: true, user: ["Hernan", 21] }`
* D. `{ admin: true }`

**[Ver soluci贸n](#sec-sol-array-34)**

---

## Reto #35: El segundo par谩metro de `JSON.stringify` {#sec-array-35}

::: {.callout-caution title="Dificultad" collapse="true"}
**Intermedio**
:::

**驴Qu茅 imprime este c贸digo?**

```js
const settings = {
  username: "asterion",
  level: 80,
  health: 25
};

const data = JSON.stringify(settings, ["level", "health"]);
console.log(data);
```

**Pista:** `JSON.stringify` convierte un objeto a cadena. 

* A. `'{"level":80, "health":25}'`
* B. `'{"username": "asterion"}'`
* C. `'["level", "health"]'`
* D. `'{"username": "asterion", "level":80, "health":25}'`

**[Ver soluci贸n](#sec-sol-array-35)**

---

## Reto #36: Alcance de variables y paso de par谩metros {#sec-array-36}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
let num = 10;

const increaseNumber = () => num++;
const increasePassedNumber = number => number++;

const num1 = increaseNumber();
const num2 = increasePassedNumber(num1);

console.log(num1);
console.log(num2);
```

**Pista:** La variable `num` tiene alcance global.

* A. `10`, `10`
* B. `10`, `11`
* C. `11`, `11`
* D. `11`, `12`

**[Ver soluci贸n](#sec-sol-array-36)**

---

## Reto #37: Multiples llamadas a una funci贸n {#sec-array-37}

::: {.callout-caution title="Dificultad" collapse="true"}
**Intermedio**
:::

**驴Qu茅 imprime este c贸digo?**

```js
const value = { number: 10 };

const multiply = (x = { ...value }) => {
  console.log((x.number *= 2));
};

multiply();
multiply();
multiply(value);
multiply(value);
```

**Pista:** Atenci贸n al objeto como par谩metro en la funci贸n y los valores por defecto.

* A. `20`, `40`, `80`, `160`
* B. `20`, `40`, `20`, `40`
* C. `20`, `20`, `20`, `40`
* D. `NaN`, `NaN`, `20`, `40`

**[Ver soluci贸n](#sec-sol-array-37)**

---

## Reto #38: `Number`, `Boolean`, `Symbol` {#sec-array-38}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
console.log(Number(2) === Number(2))
console.log(Boolean(false) === Boolean(false))
console.log(Symbol('foo') === Symbol('foo'))
```

**Pista:** Cuidado con las comparaciones entre primitivos `Symbol`.

* A. `true`, `true`, `false`
* B. `false`, `true`, `false`
* C. `true`, `false`, `true`
* D. `true`, `true`, `true`

**[Ver soluci贸n](#sec-sol-array-38)**

---

## Reto #39: Funciones as铆ncronas {#sec-array-39}

::: {.callout-caution title="Dificultad" collapse="true"}
**Intermedio**
:::

**驴Qu茅 imprime este c贸digo?**

```js
async function getData() {
  return await Promise.resolve("I made it!");
}

const data = getData();
console.log(data);
```

**Pista:** Las promesas son objetos especiales de JavaScript que solo tienen tres posibles estados: promesa resuelta, promesa rechazada o promesa pendiente.

* A. `"I made it!"`
* B. `Promise {<resolved>: "I made it!"}`
* C. `Promise {<pending>}`
* D. `undefined`

**[Ver soluci贸n](#sec-sol-array-39)**

---

## Reto #40: `Array.push` {#sec-array-40}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
function addToList(item, list) {
  return list.push(item);
}

const result = addToList("apple", ["banana"]);
console.log(result);
```

**Pista:** 驴El m茅todo `push` de los arreglos solo agrega un elemento al final de un arreglo?

* A. `['banana', 'apple']`
* B. `2`
* C. `true`
* D. `undefined`

**[Ver soluci贸n](#sec-sol-array-40)**

---

## Reto #41: `for...of` vs `for...in`  {#sec-array-41}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
const bands = ["Radiohead", "Coldplay", "Nirvana"]

for (let item in bands) {
  console.log(item)
}

for (let item of bands) {
  console.log(item)
}
```

**Pista:** Ambos sirven para iterar pero no son lo mismo.

* A. `0 1 2` y `"Radiohead" "Coldplay" "Nirvana"`
* B. `"Radiohead" "Coldplay" "Nirvana"` y `"Radiohead" "Coldplay" "Nirvana"`
* C. `"Radiohead" "Coldplay" "Nirvana"` y `0 1 2`
* D. `0 1 2` y `{0: "Radiohead", 1: "Coldplay", 2: "Nirvana"}`

**[Ver soluci贸n](#sec-sol-array-41)**

---

## Reto #42: Expresiones en elementos de arreglos {#sec-array-42}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
const list = [1 + 2, 1 * 2, 1 / 2]
console.log(list)
```

**Pista:** Los elementos de un arreglo pueden contener expresiones a ser evaluadas por el interprete de JavaScript.

* A. `["1 + 2", "1 * 2", "1 / 2"]`
* B. `["12", 2, 0.5]`
* C. `[3, 2, 0.5]`
* D. `[1, 1, 1]`

**[Ver soluci贸n](#sec-sol-array-42)**

---

## Reto #43: Olvidar el par谩metro de la funci贸n {#sec-array-43}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
function sayHi(name) {
  return `Hi there, ${name}`
}

console.log(sayHi())
```

**Pista:** No imprime ning煤n tipo de error.

* A. `Hi there`
* B. `Hi there, undefined`
* C. `Hi there, null`
* D. `ReferenceError`

**[Ver soluci贸n](#sec-sol-array-43)**

---

## Reto #44: Otra vez el alcance de las variables {#sec-array-44}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
var status = "A"

setTimeout(() => {
  const status = "B"

  const data = {
    status: "C",
    getStatus() {
      return this.status
    }
  }
  console.log(data.getStatus())
}, 0)
```

**Pista:** `var` tiene scope de funci贸n mientras que `const`scope de bloque.

* A. `"C"`
* B. `"B"`
* C. `"A"`
* D. `ReferenceError`

**[Ver soluci贸n](#sec-sol-array-44)**

---

## Reto #45: `const` y el alcance de bloque {#sec-array-45}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
function checkAge(age) {
  if (age < 18) {
    const message = "Sorry, you're too young."
  } else {
    const message = "Yay! You're old enough!"
  }
  return message
}

console.log(checkAge(21))
```

**Pista:** El valor de una variable `const` solo existe en el bloque donde fue declarada.

* A. `"Sorry, you're too young."`
* B. `"Yay! You're old enough!"`
* C. `ReferenceError`
* D. `undefined`

**[Ver soluci贸n](#sec-sol-array-45)**

---

## Reto #46: I want pizza {#sec-array-46}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
console.log("I want pizza"[0])
```

**Pista:** Las cadenas, al igual que los arreglos, son elementos iterables.

* A. `"""`
* B. `"I"`
* C. `SyntaxError`
* D. `undefined`

**[Ver soluci贸n](#sec-sol-array-46)**

---

## Reto #47: Par谩metros de funciones y valores por defecto {#sec-array-47}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
function sum(num1, num2 = num1) {
  console.log(num1 + num2)
}

sum(10)
```

**Pista:** Los par谩metros por defecto toman el valor pertinente cuando no proporcionamos el argumento correspondiente.

* A. `NaN`
* B. `20`
* C. `ReferenceError`
* D. `undefined`

**[Ver soluci贸n](#sec-sol-array-47)**

---

## Reto #48: Otra vez el m茅todo `push`  {#sec-array-48}

::: {.callout-caution title="Dificultad" collapse="true"}
**Intermedio**
:::

**驴Qu茅 imprime este c贸digo?**

```js
let newList = [1, 2, 3].push(4)

console.log(newList.push(5))
```

**Pista:** Notar que no estamos imprimiendo el arreglo `newList` suelto, sino usando el m茅todo `push`.

* A. `[1, 2, 3, 4, 5]`
* B. `[1, 2, 3, 5]`
* C. `[1, 2, 3, 4]`
* D. `TypeError: newList.push is not a function`

**[Ver soluci贸n](#sec-sol-array-48)**

---

## Reto #49: `Object.entries` para iterar objetos {#sec-array-49}

::: {.callout-caution title="Dificultad" collapse="true"}
**Intermedio**
:::

**驴Qu茅 imprime este c贸digo?**

```js
const person = {
  name: "Robert",
  age: 30
}

for (const [x, y] of Object.entries(person)) {
  console.log(x, y)
}
```

**Pista:** Notar la desestructuraci贸n de variables en el bucle `for...of`.

* A. `name Robert` y `age 30`
* B. `["name", "Robert"]` y `["age", 30]`
* C. `["name", "age"]` y `undefined`
* D. `SyntaxError`


**[Ver soluci贸n](#sec-sol-array-49)**

---

## Reto #50: Parametros REST en funciones modernas {#sec-array-50}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
function getItems(fruitList, ...args, favoriteFruit) {
  return [...fruitList, ...args, favoriteFruit]
}

getItems(["banana", "apple"], "pear", "orange")
```

**Pista:** Cuidado con el orden de los par谩metros en las funciones.

* A. `["banana", "apple", "pear", "orange"]`
* B. `[["banana", "apple"], "pear", "orange"]`
* C. `["banana", "apple", ["pear"], "orange"]`
* D. `SyntaxError`

**[Ver soluci贸n](#sec-sol-array-50)**

---

## Reto #51: Una funci贸n rara {#sec-array-51}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
function nums(a, b) {
  if
  (a > b)
  console.log('a is bigger')
  else 
  console.log('b is bigger')
  return 
  a + b
}

console.log(nums(4, 2))
console.log(nums(1, 2))
```

**Pista:** Notar que no existe ning煤n punto y coma en n煤nguna l铆nea de c贸digo de la funci贸n.

* A. `a is bigger, 6 y b is bigger, 3`
* B. `a is bigger, undefined y b is bigger, undefined`
* C. `undefined y undefined`
* D. `SyntaxError`

**[Ver soluci贸n](#sec-sol-array-51)**

---

## Reto #52: El primitivo `Symbol` {#sec-array-52}

::: {.callout-caution title="Dificultad" collapse="true"}
**Avanzado**
:::

**驴Qu茅 imprime este c贸digo?**

```js
const info = {
  [Symbol('a')]: 'b'
}

console.log(info)
console.log(Object.keys(info))
```

**Pista:** `Symbol` es un primitivo relativamente nuevo en JavaScript que permite crear valores 煤nicos e irrepetibles. 

* A. `{Symbol('a'): 'b'}` y `["{Symbol('a')"]`
* B. `{}` y `[]`
* C. `{ a: "b" }` y `["a"]`
* D. `{Symbol('a'): 'b'}` y `[]`

**[Ver soluci贸n](#sec-sol-array-52)**

---

## Reto #53: Cuidado con el return implicito de las funciones {#sec-array-53}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
const getList = ([x, ...y]) => [x, y]
const getUser = user => { name: user.name, age: user.age }

const list = [1, 2, 3, 4]
const user = { name: "Messi", age: 40 }

console.log(getList(list))
console.log(getUser(user))
```

**Pista:** Cuidado con la sintaxis de **return impl铆cito** en las funciones flecha.

* A. `[1, [2, 3, 4]]` y `SyntaxError`
* B. `[1, [2, 3, 4]]` y `{ name: "Messi", age: 40 }`
* C. `[1, 2, 3, 4]` y `{ name: "Messi", age: 40 }`
* D. `SyntaxError` y `{ name: "Messi", age: 40 }`

**[Ver soluci贸n](#sec-sol-array-53)**

---




## Reto #54: Invocar una variable como funci贸n {#sec-array-54}

::: {.callout-caution title="Dificultad" collapse="true"}
**Intermedio**
:::

**驴Qu茅 imprime este c贸digo?**

```js
const name = "Pepe"
console.log(name())
```

**Pista:** Las variables no pueden ser invocadas como funciones, 驴o si pueden?

* A. 麓SyntaxError`
* B. 麓ReferenceError`
* C. 麓TypeError`
* D. 麓undefined`

**[Ver soluci贸n](#sec-sol-array-54)**

--- 

## Reto #55: Backticks y el operador de corto circuito `and` {#sec-array-55}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
const output = `${[] && 'Im'}possible!
You should${'' && `n't`} see a therapist after so much JavaScript lol`
```

**Pista:** Recordar las tablas de verdad para saber cuando se ejecuta el operador de corto circuito.

* A. `possible! You should see a therapist after so much JavaScript lol`
* B. `Impossible! You should see a therapist after so much JavaScript lol`
* C. `possible! You shouldn't see a therapist after so much JavaScript lol`
* D. `Impossible! You shouldn't see a therapist after so much JavaScript lol`

**[Ver soluci贸n](#sec-sol-array-55)**

---

## Reto #56: El operador de corto circuito `or` {#sec-array-56}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
const one = (false || {} || null)
const two = (null || false || "")
const three = ([] || 0 || true)

console.log(one, two, three)
```

**Pista:** El operador de corto circuito 麓or麓 se ejecuta con valores **falsy**.

* A. `false` `null` `[]`
* B. `null` `""` `true`
* C. `{}` `""` `[]`
* D. `null` `null` `true`

**[Ver soluci贸n](#sec-sol-array-56)**

---

## Reto #57: Promesas y funciones as铆ncronas {#sec-array-57}

::: {.callout-caution title="Dificultad" collapse="true"}
**Avanzado**
:::

**驴Qu茅 imprime este c贸digo?**

```js
const myPromise = () => Promise.resolve('I have resolved!')

function firstFunction() {
  myPromise().then(res => console.log(res))
  console.log('second')
}

async function secondFunction() {
  console.log(await myPromise())
  console.log('second')
}

firstFunction()
secondFunction()
```

**Pista:** Recordar que cuando tenemos sintaxis `async await` escribimos c贸digo de manera s铆ncrona pero se ejecuta de manera as铆ncrona.

* A. `I have resolved!`, `second` y `I have resolved!`, `second`
* B. `second`, `I have resolved!` y `second`, `I have resolved!`
* C. `I have resolved!`, `second` y `second`, `I have resolved!`
* D. `second`, `I have resolved!` y `I have resolved!`, `second`

**[Ver soluci贸n](#sec-sol-array-57)**

---

## Reto #58: Conjuntos en JavaScript {#sec-array-58}

::: {.callout-caution title="Dificultad" collapse="true"}
**Avanzado**
:::

**驴Qu茅 imprime este c贸digo?**

```js
const set = new Set()

set.add(1)
set.add("Cris")
set.add({ name: "Cris" })

for (let item of set) {
  console.log(item + 2)
}
```

**Pista:** Recordar que el operador `+` puede ser usado para sumar n煤meros y para concatenar cadenas de texto.

* A. `3`, `NaN`, `NaN`
* B. `3`, `7`, `NaN`
* C. `3`, `Cris2`, `[Object object]2`
* D. `"12"`, `Cris2`, `[Object object]2`

**[Ver soluci贸n](#sec-sol-array-58)**

---

## Reto #59: Objetos y sus referencias {#sec-array-59}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
function compareMembers(person1, person2 = person) {
  if (person1 !== person2) {
    console.log("Not the same!")
  } else {
    console.log("They are the same!")
  }
}

const person = { name: "Allan" }

compareMembers(person)
```

**Pista:** Cuidado con las referencias de los objetos.

* A. `Not the same!`
* B. `They are the same!`
* C. `ReferenceError`
* D. `SyntaxError`

**[Ver soluci贸n](#sec-sol-array-59)**

---

## Reto #60: Acceso a propiedades de objetos {#sec-array-60}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
const colorConfig = {
  red: true,
  blue: false,
  green: true,
  black: true,
  yellow: false,
}

const colors = ["pink", "red", "blue"]

console.log(colorConfig.colors[1])
```

**Pista:** Recuerda que las propiedades de los objetos son accedidas por medio de `.` y los arreglos son accedidos por medio de `[]`.

* A. `true`
* B. `false`
* C. `undefined`
* D. `TypeError`

**[Ver soluci贸n](#sec-sol-array-60)**

---

## Reto #61: M茅todos de arreglo inmutables {#sec-array-61}

::: {.callout-caution title="Dificultad" collapse="true"}
**Intermedio**
:::

**驴Cu谩l o cuales de estos m茅todos modifica el array original?**

```js
const points = ['.', '..', '...']

emojis.map(x => x + '.')
emojis.filter(x => x !== '..')
emojis.find(x => x !== '..')
emojis.reduce((acc, cur) => acc + '.')
emojis.slice(1, 2, '.') 
emojis.splice(1, 2, '.')
```

**Pista:** Los m茅todos inmutables no modifican el arreglo original.

* A. `Todos los anteriores`
* B. `map`, `reduce`, `slice`, `splice`
* C. `map`, `slice`, `splice`
* D. `splice`

**[Ver soluci贸n](#sec-sol-array-61)**

---

## Reto #62: Acceso a propiedades de objetos y elementos de arreglos {#sec-array-62}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
const food = ['pizza', 'chocolat', 'avocat', 'egg']
const info = { favoriteFood: food[0] }

info.favoriteFood = 'apple'

console.log(food)
```

**Pista:** La notaci贸n de punto sirve para acceder a propiedades de objetos y la notaci贸n de corchetes para acceder a elementos de arreglos.

* A. `['pizza', 'chocolat', 'avocat', 'egg']`
* B. `['apple', 'chocolat', 'avocat', 'egg']`
* C. `['apple', 'pizza', 'chocolat', 'avocat', 'egg']`
* D. `ReferenceError`

**[Ver soluci贸n](#sec-sol-array-62)**

---

## Reto #63: Temporal Dead Zone {#sec-array-63}

::: {.callout-caution title="Dificultad" collapse="true"}
**Avanzado**
:::

**驴Qu茅 imprime este c贸digo?**

```js
let name = 'Abigail'

function getName() {
  console.log(name)
  let name = 'Norah'
}

getName()
```

**Pista:** Cuidado con los scopes de las variables, no es lo mismo una variable con scope global y una variable con scope de bloque.

* A. `Abigail`
* B. `Norah`
* C. `undefined`
* D. `ReferenceError`

**[Ver soluci贸n](#sec-sol-array-63)**

---

## Reto #64: Interpolaci贸n de cadenas {#sec-array-64}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
console.log(`${(x => x)('I love')} to program`)
```

**Pista:** En las plantillas con backticks, todo lo que este dentro de `{}` se evalua como una expresi贸n de JavaScript.

* A. `I love to program`
* B. `undefined to program`
* C. `${(x => x)('I love') to program`
* D. `TypeError`

**[Ver soluci贸n](#sec-sol-array-64)**

---

## Reto #65: `typeof` y funciones {#sec-array-65}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
const sayHi = () => {
  return (() =>"Hi Javascript!")();
}

console.log(typeof sayHi());
```

**Pista:** Ojo con el valor de retorno de la funci贸n `sayHi`.

* A. `number`
* B. `object`
* C. `string`
* D. `TypeError`

**[Ver soluci贸n](#sec-sol-array-65)**

---

## Reto #66: Logical Nullish Assignment {#sec-array-66}

::: {.callout-caution title="Dificultad" collapse="true"}
**Intermedio**
:::

**驴Qu茅 imprime este c贸digo?**

```js
const getName = (obj) => {
  obj.name ??= "not name";
  return obj;
}
console.log(getName({}))
```

**Pista:** Recuerda que un valor **nullish** es aquel que evalua `undefined` o `null`.

* A. `undefined`
* B. `{}`
* C. `{ name:"not name" }`
* D. `Ninguno de los anteriores`

**[Ver soluci贸n](#sec-sol-array-66)**

---

## Reto #67: Actulizar propiedades de objetos {#sec-array-67}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
const person = {
  id: 1,
  name:"Fernando",
};
person.name = "Pedro";
console.log(persona.nombre);
```

**Pista:** Podemos actualizar valores de una propiedad de un objeto con la notaci贸n de punto.

* A. `Pedro`
* B. `Fernando`
* C. `null`
* D. `TypeError`

**[Ver soluci贸n](#sec-sol-array-67)**

---

## Reto #68: Operador `in` y eliminaci贸n de propiedades {#sec-array-68}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
const band = {
  id:1,
  name: "Radiohead",
  "type of music": "Rock",
  albums: ["Pablo Honey", "Ok Computer", "In Rainbows"]
};

band.voice = undefined;
console.log("voice" in band);
delete band["type of music"];
console.log("type of music" in band);
```

**Pista:** `in` sirve para poder verificar si una propiedad existe en un objeto.

* A. `false`, `false`
* B. `true`, `false`
* C. `false`, `true`
* D. `undefined`, `true`

**[Ver soluci贸n](#sec-sol-array-68)**

---

## Reto #69: Propiedades din谩micas de objetos {#sec-array-69}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
const band = {
  id:1,
  name: "Radiohead",
  "tipe of music": "Rock",
  albums: ["Pablo Honey", "Ok Computer", "In Rainbows"]
};

console.log(band["na"+"me"])
```

**Pista:** La notaci贸n de corchetes en los objetos permite acceder a propiedades usando una expresi贸n como clave.

* A. `Radiohead`
* B. `undefined`
* C. `name`
* D. `SyntaxError`

**[Ver soluci贸n](#sec-sol-array-69)**

---

## Reto #70: M谩s objetos y valores por referencia {#sec-array-70}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
let objeto1 = { valor: 10 };
let objeto2 = objeto1;
let objeto3 = { valor: 10 };

console.log(objeto1 == objeto2);
console.log(objeto1 == objeto3);

objeto1.valor = 15;
console.log(objeto2.valor);
console.log(objeto3.valor);
```

**Pista:** Recuerda c贸mo funcionan las referencias en JavaScript con los objetos. Piensa en c贸mo se comportan las asignaciones de objetos y las comparaciones de igualdad con el operador `==`.

* A. `true`, `false`, `15`, `10`
* B. `false`, `true`, `10`, `20`
* C. `true`, `true`, `15`, `20`
* D. `false`, `false`, `20`, `15`

**[Ver soluci贸n](#sec-sol-array-70)**

---


## Reto #71: `const` en primitivos y objetos {#sec-array-71}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
const name = "Cristian";
name = "Fernando";
console.log(name)

const person = {
  id: 1,
  name: "Cristian",
};

person.name = "Fernando";
console.log(person.name);
```

**Pista:** `const` actua diferente en objetos y primitivos.

* A. `Fernando`, `Fernando`
* B. `Cristian`, `TypeError`
* C. `Cristian`, `Fernando`
* D. `TypeError`, `Fernando`

**[Ver soluci贸n](#sec-sol-array-71)**

---

## Reto #72: `length` en cadenas y arreglos {#sec-array-72}

::: {.callout-caution title="Dificultad" collapse="true"}
**Intermedio**
:::

**驴Qu茅 imprime este c贸digo?**

```js
const band = "Coldplay";
const songs = ["Yellow", "Fix You", "Trouble"];

console.log(band["length"]);
console.log(songs["len"+"gth"]);
```

**Pista:** `length` sirve para calcular la longitud de un iterable como una cadena o un arreglo.

* A. `length`, `3`
* B. `8`, `SyntaxError`
* C. `8`, `3`
* D. `SyntaxError`, `SyntaxError`


**[Ver soluci贸n](#sec-sol-array-72)**

---

## Reto #73: Corto circuito y nullish coalescing operator  {#sec-array-73}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
console.log(undefined || "0" || null || (undefined ?? 0))
```

**Pista:** El operador `??` se ejecuta solo si evalua como `undefined` o `null`.

* A. `0`
* B. `"0"`
* C. `undefined`
* D. `null`

**[Ver soluci贸n](#sec-sol-array-73)**

---

## Reto #74: Restas de cadenas y n煤meros {#sec-array-74}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
console.log(typeof("22" - 0))
```

**Pista:** El operdor `-` siempre representa una resta aritm茅tica en JavaScript.

* A. `number`
* B. `string`
* C. `object`
* D. `TypeError`

**[Ver soluci贸n](#sec-sol-array-74)**

---

## Reto #75: `length` como un setter {#sec-array-75}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
const numbers = [1, 2, 3, 4, 5];
numbers.length = 0;
console.log(numbers);
```

**Pista:** `length` no solo sirve para calcular la longitud de un iterable, tambi茅n puede usarse para establecer el n煤mero de elementos.

* A. `1`
* B. `0`
* C. `[]`
* D. `[1]`

**[Ver soluci贸n](#sec-sol-array-75)**

---

## Reto #76: 驴`typeof` para arreglos?  {#sec-array-76}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
const arr = [];
console.log(Array.isArray(arr));
```

**Pista:** `Array.isArray` es un m茅todo que nos permite comprobar si una variable es un arreglo o no.

* A. `true`
* B. `false`
* C. `[]`
* D. `ReferenceError`

**[Ver soluci贸n](#sec-sol-array-76)**

---

## Reto #77: `null` vs `object`  {#sec-array-77}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
console.log(typeof null == 'object');
```

**Pista:** Este reto representa un bug cl谩sico de JavaScript. Cuidado al comparar `null` con `object`.

* A. `true`
* B. `false`
* C. `TypeError`
* D. `undefined`

**[Ver soluci贸n](#sec-sol-array-77)**

---

## Reto #78: Multiples maneras de expandir cadenas {#sec-array-78}

::: {.callout-caution title="Dificultad" collapse="true"}
**Intermedio**
:::

**驴Qu茅 imprime este c贸digo?**

```js
const name = "Alejandro";

console.log(name.split(""));
console.log([...name]);
console.log(Array.from(name));
```

**Pista:** Existen muchos caminos para llegar a Roma.

* A. Los 3 imprimen: `['A','l','e','j','a','n','d','r','o']`
* B. `['A','l','e','j','a','n','d','r','o']` , `[]`, `['A','l','e','j','a','n','d','r','o']`
* C. `['Alejandro']` , `['A','l','e','j','a','n','d','r','o']`, 
`['A','l','e','j','a','n','d','r','o']`
* D. `Alejandro`, `Alejandro`, `Alejandro`

**[Ver soluci贸n](#sec-sol-array-78)**

---

## Reto #79: Invertir una cadena con `split`, `reverse` y `join` {#sec-array-79}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
console.log("hello".split("").reverse().join("")); 
```

**Pista:** Cuidado con imprimir una cadena o un arreglo. Ojo al 岣etodo `join`.

* A. `['h','e','l','l','o'];`
* B. `['o','l','l','e','h']`
* C. `"hello"`
* D. `"olleh"`

**[Ver soluci贸n](#sec-sol-array-79)**

---

## Reto #80: Higher Order Functions {#sec-array-80}

::: {.callout-caution title="Dificultad" collapse="true"}
**Intermedio**
:::

**驴Qu茅 imprime este c贸digo?**

```js
//A
const multiply = a => b => a * b ;

//B
const test = (name, action) => {
  return action(name); 
}
console.log(test("Ana", console.log)); 
//Ana (por consola)
```

**Pista:** Las Higher Order Functions son aquellas que pueden recibir funciones como par谩metros o regresar funciones.

* A. `multiply`
* B. `test`
* C. `Ambas`
* D. `Ninguna`

**[Ver soluci贸n](#sec-sol-array-80)**

---

## Reto #81: El m茅todo `flat` de los arreglos {#sec-array-81}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
const numbers = [1, 2, [3, 4], 5, 6, [7, 8], 9, 0];
console.log(numbers.flat());
```

**Pista:** `flat` permite aplanar arreglos en JavaScript.

* A. `Error, el m茅todo flat no existe.`
* B. `[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]`
* C. `[1, 2, 3, 4, 5, 6, [7, 8], 9, 0]`
* D. `[1, 2, [3, 4], 5, 7, 8, 9, 0]`

**[Ver soluci贸n](#sec-sol-array-81)**

---

## Reto #82: El m茅todo `repeat` de las cadenas {#sec-array-82}

::: {.callout-caution title="Dificultad" collapse="true"}
**Intermedio**
:::

**驴Qu茅 imprime este c贸digo?**

```js
console.log("--- Menu ---");
console.log("tea" + ".".repeat(5) + ":" + "$1.50");
console.log("coffee" + ".".repeat(3.2) + ":" + "$3.75");
console.log("beer" + ".".repeat(-1) + ":" + "$5.00");
```

**Pista:** `repeat` es un m茅todo de cadenas poco conocido pero muy 煤til para repetir cadenas de manera controlada.

* A. 

```js
--- Menu ---
tea.....:$1.50
coffee..:$3.75
RangeError: repeat count must be non-negative
```
* B. 

```js
--- Menu ---
tea.....:$1.50
coffee..:$3.75
beer....:$5.00
```

* C. 

```js
--- Men煤 ---
t茅.....:$1.50
RangeError: repeat count must be non-decimal numbers
RangeError: repeat count must be non-negative numbers
```

**[Ver soluci贸n](#sec-sol-array-82)**

---

## Reto #83: `var`, `let` y `const` y el alcance global {#sec-array-83}

::: {.callout-caution title="Dificultad" collapse="true"}
**B谩sico**
:::

**驴Qu茅 imprime este c贸digo?**

```js
var name = "Camila";
let lastName = "Rodriguez";
const age = 25;

const getPersonalData = () => {
  console.log(name);
  console.log(lastName);
  console.log(age);
}

console.log(getPersonalData());
```

**Pista:** Diferenciar entre alcance global y de bloque.

* A. `Camila`, `Rodriguez`, `25`
* B. `Camila`, `undefined`, `undefined`
* C. `ReferenceError`
* D. `undefined`, `Rodriguez`, `25`

**[Ver soluci贸n](#sec-sol-array-83)**

---

## Reto #84: Trailing commas {#sec-array-84}

::: {.callout-caution title="Dificultad" collapse="true"}
**Intermedio**
:::

**Explica este c贸digo JavaScript**

Nota que en la l铆nea `age:7,` termina con `,` pero no hay ninguna sentencia del objeto `dog` despu茅s 

```js
const dog = {
  id:1,
  name:"Boby",
  age:7,
};
```

**Pista:** Esta sintaxis es com煤n en lenguajes modernos para facilitar el control de versiones al a帽adir nuevos elementos sin modificar l铆neas anteriores.

* A. `El c贸digo es incorrecto, no es posible escribir una , al final de una sentencia de objeto.`
* B. `El c贸digo es correcto, esta caracter铆stica de JavaScript se denomina Trailing commas y es perfectamente v谩lido.`

**[Ver soluci贸n](#sec-sol-array-84)**

---

## Reto #85: Algo raro pasa con las palabras reservadas {#sec-array-85}

::: {.callout-caution title="Dificultad" collapse="true"}
**Intermedio**
:::

**驴Qu茅 imprime este c贸digo?**

```js
const test = {
  if:"It's a conditional",
  let: "It's a way to declare variables",
  for: "It's a loop",
};
console.log(test.for); 
```

**Pista:** Cuidado con el uso de palabras reservadas como nombres de `keys` en objetos.

* A. `SyntaxError: unexpected token: keyword 'for'`
* B. `Es un bucle`
* C. `ReferenceError`
* D. `Ninguna de las anteriores`

**[Ver soluci贸n](#sec-sol-array-85)**

---

## Reto #86: {#sec-array-86}

::: {.callout-caution title="Dificultad" collapse="true"}
**Intermedio**
:::

**驴Qu茅 imprime este c贸digo?**

```js

```

**Pista:** 

* A. `multiply`
* B. `test`
* C. `Ambas`
* D. `Ninguna`

**[Ver soluci贸n](#sec-sol-array-86)**

---

## Reto #87: {#sec-array-87}

::: {.callout-caution title="Dificultad" collapse="true"}
**Intermedio**
:::

**驴Qu茅 imprime este c贸digo?**

```js

```

**Pista:** 

* A. `multiply`
* B. `test`
* C. `Ambas`
* D. `Ninguna`

**[Ver soluci贸n](#sec-sol-array-87)**

---

## Reto #88: {#sec-array-88}

::: {.callout-caution title="Dificultad" collapse="true"}
**Intermedio**
:::

**驴Qu茅 imprime este c贸digo?**

```js

```

**Pista:** 

* A. `multiply`
* B. `test`
* C. `Ambas`
* D. `Ninguna`

**[Ver soluci贸n](#sec-sol-array-88)**

---

## Reto #89: {#sec-array-89}

::: {.callout-caution title="Dificultad" collapse="true"}
**Intermedio**
:::

**驴Qu茅 imprime este c贸digo?**

```js

```

**Pista:** 

* A. `multiply`
* B. `test`
* C. `Ambas`
* D. `Ninguna`

**[Ver soluci贸n](#sec-sol-array-89)**

---

## Reto #90: {#sec-array-90}

::: {.callout-caution title="Dificultad" collapse="true"}
**Intermedio**
:::

**驴Qu茅 imprime este c贸digo?**

```js

```

**Pista:** 

* A. `multiply`
* B. `test`
* C. `Ambas`
* D. `Ninguna`

**[Ver soluci贸n](#sec-sol-array-90)**

---

## Reto #91: {#sec-array-91}

::: {.callout-caution title="Dificultad" collapse="true"}
**Intermedio**
:::

**驴Qu茅 imprime este c贸digo?**

```js

```

**Pista:** 

* A. `multiply`
* B. `test`
* C. `Ambas`
* D. `Ninguna`

**[Ver soluci贸n](#sec-sol-array-91)**

---

## Reto #92: {#sec-array-92}

::: {.callout-caution title="Dificultad" collapse="true"}
**Intermedio**
:::

**驴Qu茅 imprime este c贸digo?**

```js

```

**Pista:** 

* A. `multiply`
* B. `test`
* C. `Ambas`
* D. `Ninguna`

**[Ver soluci贸n](#sec-sol-array-92)**

---

## Reto #93: {#sec-array-93}

::: {.callout-caution title="Dificultad" collapse="true"}
**Intermedio**
:::

**驴Qu茅 imprime este c贸digo?**

```js

```

**Pista:** 

* A. `multiply`
* B. `test`
* C. `Ambas`
* D. `Ninguna`

**[Ver soluci贸n](#sec-sol-array-93)**

---

## Reto #94: {#sec-array-94}

::: {.callout-caution title="Dificultad" collapse="true"}
**Intermedio**
:::

**驴Qu茅 imprime este c贸digo?**

```js

```

**Pista:** 

* A. `multiply`
* B. `test`
* C. `Ambas`
* D. `Ninguna`

**[Ver soluci贸n](#sec-sol-array-94)**

---

## Reto #95: {#sec-array-95}

::: {.callout-caution title="Dificultad" collapse="true"}
**Intermedio**
:::

**驴Qu茅 imprime este c贸digo?**

```js

```

**Pista:** 

* A. `multiply`
* B
